spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    filter: true
    show-common-extensions: true
  show-actuator: true
