--
-- PostgreSQL database dump
--

\restrict lfLq3gt1BHajWBqWjkKPQbOi7gkyaRUC8LVkbGRa8FRMzKqBnbJ9TgPTWHUpJ69

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-07-18 17:33:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16476)
-- Name: cours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cours (
    id bigint NOT NULL,
    credits integer NOT NULL,
    description character varying(255),
    titre character varying(255),
    enseignant_id bigint
);


ALTER TABLE public.cours OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16475)
-- Name: cours_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16486)
-- Name: enseignants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enseignants (
    id bigint NOT NULL,
    email character varying(255),
    nom character varying(255),
    prenom character varying(255),
    specialite character varying(255)
);


ALTER TABLE public.enseignants OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16485)
-- Name: enseignants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enseignants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enseignants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16495)
-- Name: etudiants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etudiants (
    id bigint NOT NULL,
    email character varying(255),
    matricule character varying(255),
    nom character varying(255),
    prenom character varying(255),
    telephone character varying(255),
    user_id bigint,
    document_url character varying(255),
    photo_url character varying(255)
);


ALTER TABLE public.etudiants OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16494)
-- Name: etudiants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.etudiants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.etudiants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16504)
-- Name: inscriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inscriptions (
    id bigint NOT NULL,
    date_inscription date,
    cours_id bigint,
    etudiant_id bigint
);


ALTER TABLE public.inscriptions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16503)
-- Name: inscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16511)
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(500) NOT NULL,
    user_id bigint
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16510)
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16522)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    nom character varying(255),
    password character varying(255) NOT NULL,
    prenom character varying(255),
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'ENSEIGNANT'::character varying, 'ETUDIANT'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16521)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5053 (class 0 OID 16476)
-- Dependencies: 220
-- Data for Name: cours; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cours (id, credits, description, titre, enseignant_id) FROM stdin;
1	6	Conception et développement d'une API REST sécurisée	Développement Web Full-Stack	1
2	4	Notions de base en Administration Reseau	Administration Reseau	2
\.


--
-- TOC entry 5055 (class 0 OID 16486)
-- Dependencies: 222
-- Data for Name: enseignants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.enseignants (id, email, nom, prenom, specialite) FROM stdin;
1	abdoulaye@example.com	ly	Abdoulaye	spring
2	khalifagueye@example.com	gueye	khalifa	RESEAU
\.


--
-- TOC entry 5057 (class 0 OID 16495)
-- Dependencies: 224
-- Data for Name: etudiants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.etudiants (id, email, matricule, nom, prenom, telephone, user_id, document_url, photo_url) FROM stdin;
1	maridiallo@example.com	MAT20260716	diallo	Marie	771234567	\N	\N	\N
2	mamadou.diallo@example.com	MAT202401002	Diallo	Mamadou	+221771234567	\N	\N	\N
3	aida.sarr@example.com	MAT202401003	Sarr	Aida	+221772345678	\N	\N	\N
4	cheikh.ndour@example.com	MAT202401004	Ndour	Cheikh	+221773456789	\N	\N	\N
5	rokhaya.faye@example.com	MAT202401005	Faye	Rokhaya	+221774567890	\N	\N	\N
\.


--
-- TOC entry 5059 (class 0 OID 16504)
-- Dependencies: 226
-- Data for Name: inscriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inscriptions (id, date_inscription, cours_id, etudiant_id) FROM stdin;
\.


--
-- TOC entry 5061 (class 0 OID 16511)
-- Dependencies: 228
-- Data for Name: refresh_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_token (id, expiry_date, token, user_id) FROM stdin;
9	2026-07-23 18:28:41.811781+00	d6747a16-1f15-4e28-92bd-450d8b83d66b	2
8	2026-07-24 17:20:26.678782+00	0d895c94-ee5d-445d-b386-313b6c9b582c	1
\.


--
-- TOC entry 5063 (class 0 OID 16522)
-- Dependencies: 230
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, nom, password, prenom, role) FROM stdin;
1	khalilfall52@gmail.com	fall	$2a$10$9rnxgxIFlS7eT4n/M.GGh.qJpM8udVPPCp07E1eHa4I09Apk4YZbC	khalil	ADMIN
2	mammadiallo@gmail.com	mamma	$2a$10$4uJmcFalBQo3rRCtIlRkOeRTjzYjrOrMbSum2RGLDkcf.qXZRoRdS	diallo	ETUDIANT
\.


--
-- TOC entry 5069 (class 0 OID 0)
-- Dependencies: 219
-- Name: cours_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cours_id_seq', 2, true);


--
-- TOC entry 5070 (class 0 OID 0)
-- Dependencies: 221
-- Name: enseignants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.enseignants_id_seq', 2, true);


--
-- TOC entry 5071 (class 0 OID 0)
-- Dependencies: 223
-- Name: etudiants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.etudiants_id_seq', 6, true);


--
-- TOC entry 5072 (class 0 OID 0)
-- Dependencies: 225
-- Name: inscriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inscriptions_id_seq', 1, false);


--
-- TOC entry 5073 (class 0 OID 0)
-- Dependencies: 227
-- Name: refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_token_id_seq', 9, true);


--
-- TOC entry 5074 (class 0 OID 0)
-- Dependencies: 229
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- TOC entry 4883 (class 2606 OID 16484)
-- Name: cours cours_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cours
    ADD CONSTRAINT cours_pkey PRIMARY KEY (id);


--
-- TOC entry 4885 (class 2606 OID 16493)
-- Name: enseignants enseignants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enseignants
    ADD CONSTRAINT enseignants_pkey PRIMARY KEY (id);


--
-- TOC entry 4887 (class 2606 OID 16502)
-- Name: etudiants etudiants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etudiants
    ADD CONSTRAINT etudiants_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 16509)
-- Name: inscriptions inscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscriptions
    ADD CONSTRAINT inscriptions_pkey PRIMARY KEY (id);


--
-- TOC entry 4891 (class 2606 OID 16520)
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4897 (class 2606 OID 16539)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4893 (class 2606 OID 16537)
-- Name: refresh_token ukf95ixxe7pa48ryn1awmh2evt7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukf95ixxe7pa48ryn1awmh2evt7 UNIQUE (user_id);


--
-- TOC entry 4895 (class 2606 OID 16535)
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- TOC entry 4899 (class 2606 OID 16533)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 16540)
-- Name: cours fkfyonv6ewc19w0y7yu5kmleulg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cours
    ADD CONSTRAINT fkfyonv6ewc19w0y7yu5kmleulg FOREIGN KEY (enseignant_id) REFERENCES public.enseignants(id);


--
-- TOC entry 4904 (class 2606 OID 16560)
-- Name: refresh_token fkjtx87i0jvq2svedphegvdwcuy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4902 (class 2606 OID 16555)
-- Name: inscriptions fkrbdv2i5mc55pqxpuwt4fgxdbh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscriptions
    ADD CONSTRAINT fkrbdv2i5mc55pqxpuwt4fgxdbh FOREIGN KEY (etudiant_id) REFERENCES public.etudiants(id);


--
-- TOC entry 4901 (class 2606 OID 16545)
-- Name: etudiants fksgxlwybt9svpg1vi17i44695h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etudiants
    ADD CONSTRAINT fksgxlwybt9svpg1vi17i44695h FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4903 (class 2606 OID 16550)
-- Name: inscriptions fkt3re4dbtj2w5601e98q0ohhjl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inscriptions
    ADD CONSTRAINT fkt3re4dbtj2w5601e98q0ohhjl FOREIGN KEY (cours_id) REFERENCES public.cours(id);


-- Completed on 2026-07-18 17:33:11

--
-- PostgreSQL database dump complete
--

\unrestrict lfLq3gt1BHajWBqWjkKPQbOi7gkyaRUC8LVkbGRa8FRMzKqBnbJ9TgPTWHUpJ69
